# *****************************************************************
# *          ESPHome Custom Component Modbus sniffer for          *
# *              Delta Solvia Inverter 3.0 EU G4 TR               *
# *             installed with Solivia Gateway M1 D2.             *
# *****************************************************************
#
# This was originally made by htvekov https://github.com/htvekov/solivia_esphome
# I have changed it to G3 inverter and without Solivia GW and added that data can be retrieved from several inverters
#
#
# Remember to copy the Custom Component solivia.h file to the ESPHome folder in
# Home Assistant !!
#
# This config doesn't send any commands to the inverter !!
# Instead it relies on the gateways constant request for data (appx. 1 package pr. second).
#
# If you don't have a gateway, the package request can instead easily be send from
# ESPHome using uart.write and eg. triggered via the ESPHome Time component.
#
# Example:
# time:
#   - platform: homeassistant
#     id: esptime
#   - platform: sntp
#     on_time:
#        # Request package every 10 seconds from inverter at slave address: 0x01
#       - seconds: /10
#         then:
#           - uart.write: [0x02, 0x05, 0x01, 0x02, 0x60, 0x01, 0x85, 0xFC, 0x03]
# 
#
# NOTE !!
# My inverter, unlike most examples found on the net, returns a 255 bytes
# response. Most common inverter response length is 150 bytes (0x96) or 157 (0x9D).
# So almost all commands/registers do not match other examples on the net.
# Package structure is also somewhat different.
#
# Below the actual ESPHome config, you'll find a compiled list of all registers
# I've identified. Those marked with a question mark are not confirmed,
# but an 'educated guess' only.
#
# Tested on both ESP8266 with software uart and ESP32 with hardware uart.
# I experience no issues in production with the ESP8266 software uart.
# Not even with debug uart logging active.
#
# My config:
# Inverter part no.: EOE46010287
# Single string input PV1: 3500W
# Single phase output: L1
# Slave address: 0x01
# Baud rate: 19200
# Install country: Denmark
#
# Gateway request: 02:05:01:02:60:01:85:FC:03
# Inverter response: 02:06:01:FF:60:01 + 255 data bytes (incl. CRC bytes) + ETX byte
#
# Actually the response doesn't match the protocol, as the CRC bytes and trailing
# ETX byte should be excluded from data length identifier (0xff)
# Here, strangely enough, the CRC is included, but not the ETX ?
#
# A few of the 'public known' commands have been tested. Most unfortunately did fail.
# Haven't really spend much time on testing further commands, as all the data
# i need is in gateway package.
# But commmand for eg. inverters serial no. is working ok on my inverter.
# - uart.write: [0x02, 0x05, 0x01, 0x02, 0x00, 0x01, 0xAD, 0xFC, 0x03] will response
# correctly with serial no.


esphome:
  name: "delta-solivia-G3"
  platform: ESP8266
  board: d1_mini
  includes:
    - solivia-G3.h
    
# Enable logging
logger:
#level: VERBOSE
  #baud_rate: 0

# Enable Home Assistant API
api:

ota:
  password: "my_ota_password"

wifi:
  ssid: 'xxxx'
  password: 'xxxx'

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solivia_G3 Fallback Hotspot"
    password: "my_fallback_password"

captive_portal:

# Remove hash signs and activate, if you don't have a Solivia gataway.
# With this you emulate the gateways request for data response from the inverter.
# With settings below, the requests are send every 10 seconds.
#
time:
  - platform: homeassistant
    id: esptime
  - platform: sntp
    on_time:
       # Request package every 10 seconds from inverter at slave address: 0x01
      - seconds: 1/3
        then:
          - uart.write: [0x02, 0x05, 0x01, 0x02, 0x60, 0x01, 0x85, 0xFC, 0x03]
      - seconds: 2/3
        then:
          - uart.write: [0x02, 0x05, 0x02, 0x02, 0x60, 0x01, 0x85, 0xB8, 0x03]
      - seconds: 3/3
        then:
          - uart.write: [0x02, 0x05, 0x03, 0x02, 0x60, 0x01, 0x84, 0x44, 0x03]

binary_sensor:
  - platform: status
    name: "Solivia Node Status"
    id: solivia_status
 
uart:
  id: mod_bus
  # tx_pin: 17 # Typical tx pin for hardware UART#2 on ESP32 modules
  # rx_pin: 16 # Typical rx pin for hardware UART#2 on ESP32 modules
  tx_pin: 5 # D2 ESP8266 tx pin for soft serial uart
  rx_pin: 4 # D1 ESP8266 rx pin for soft serial uart
  # Increase buffer size as total package we're sniffing is 262 bytes in total
  # Inverter reply: 6 bytes + Data: 255 bytes + ETX: 1 byte = 262 bytes
  rx_buffer_size: 512
  baud_rate: 19200
  parity: NONE
  stop_bits: 1
  #debug: # Activate if you need to investigate package details in the log

sensor:
- platform: custom
  lambda: |-
    auto delta = new soliviag3(id(mod_bus));
    App.register_component(delta);
    return {delta->pv1_ac_power, delta->pv1_d_yield, delta->pv1_dc_a, delta->pv1_dc_v, delta->pv1_ac_a, delta->pv1_ac_v, delta->pv1_hs_1, delta->pv1_hs_2, delta->pv1_iso_plus, delta->pv1_iso_minus, delta->pv2_ac_power, delta->pv2_d_yield, delta->pv2_dc_a, delta->pv2_dc_v, delta->pv2_ac_a, delta->pv2_ac_v, delta->pv2_hs_1, delta->pv2_hs_2, delta->pv2_iso_plus, delta->pv2_iso_minus, delta->pv3_ac_power, delta->pv3_d_yield, delta->pv3_dc_a, delta->pv3_dc_v, delta->pv3_ac_a, delta->pv3_ac_v, delta->pv3_hs_1, delta->pv3_hs_2, delta->pv3_iso_plus, delta->pv3_iso_minus};
  sensors:
  - name: "PV1 AC power"
    icon: mdi:power-plug
    device_class: energy
    unit_of_measurement: W
    accuracy_decimals: 0
    # Frequent update, as sensor is used to calculate consumption with iem3155 sensor.total_active_power
    filters:
    - throttle: 10s 
  
  - name: "PV1 Solar daily yield"
    icon: mdi:chart-line
    device_class: energy
    # Set state_class in order for HA to use sensor in the Energy component
    state_class: total_increasing
    unit_of_measurement: Wh
    accuracy_decimals: 0
    filters:
    - throttle: 10s
    - multiply: 10
  
  - name: "PV1 DC current"
    device_class: energy
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
    - throttle: 10s
    - multiply: 0.1
  
  - name: "PV1 DC voltage"
    device_class: energy
    unit_of_measurement: V
    accuracy_decimals: 0
    filters:
    - throttle: 10s
  
  - name: "PV1 AC current"
    device_class: energy
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
    - throttle: 10s
    - multiply: 0.1
  
  - name: "PV1 AC voltage"
    device_class: energy
    unit_of_measurement: V
    accuracy_decimals: 0
    filters:
    - throttle: 10s
  
  - name: "PV1 Heat sink #1"
    device_class: temperature
    unit_of_measurement: °C
    filters:
    - throttle: 10s
  
  - name: "PV1 Heat sink #2"
    device_class: temperature
    unit_of_measurement: °C
    filters:
    - throttle: 10s

  - name: "PV1 ISO +"
    device_class: energy
    unit_of_measurement: kΩ
    filters:
    - throttle: 10s
  
  - name: "PV1 ISO -"
    device_class: energy
    unit_of_measurement: kΩ
    filters:
    - throttle: 10s

  - name: "PV2 AC power"
    icon: mdi:power-plug
    device_class: energy
    unit_of_measurement: W
    accuracy_decimals: 0
    # Frequent update, as sensor is used to calculate consumption with iem3155 sensor.total_active_power
    filters:
    - throttle: 10s 
  
  - name: "PV2 Solar daily yield"
    icon: mdi:chart-line
    device_class: energy
    # Set state_class in order for HA to use sensor in the Energy component
    state_class: total_increasing
    unit_of_measurement: Wh
    accuracy_decimals: 0
    filters:
    - throttle: 10s
    - multiply: 10
  
  - name: "PV2 DC current"
    device_class: energy
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
    - throttle: 10s
    - multiply: 0.1
  
  - name: "PV2 DC voltage"
    device_class: energy
    unit_of_measurement: V
    accuracy_decimals: 0
    filters:
    - throttle: 10s
  
  - name: "PV2 AC current"
    device_class: energy
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
    - throttle: 10s
    - multiply: 0.1
  
  - name: "PV2 AC voltage"
    device_class: energy
    unit_of_measurement: V
    accuracy_decimals: 0
    filters:
    - throttle: 10s
  
  - name: "PV2 Heat sink #1"
    device_class: temperature
    unit_of_measurement: °C
    filters:
    - throttle: 10s
  
  - name: "PV2 Heat sink #2"
    device_class: temperature
    unit_of_measurement: °C
    filters:
    - throttle: 10s

  - name: "PV2 ISO +"
    device_class: energy
    unit_of_measurement: kΩ
    filters:
    - throttle: 10s
  
  - name: "PV2 ISO -"
    device_class: energy
    unit_of_measurement: kΩ
    filters:
    - throttle: 10s

  - name: "PV3 AC power"
    icon: mdi:power-plug
    device_class: energy
    unit_of_measurement: W
    accuracy_decimals: 0
    # Frequent update, as sensor is used to calculate consumption with iem3155 sensor.total_active_power
    filters:
    - throttle: 10s 
  
  - name: "PV3 Solar daily yield"
    icon: mdi:chart-line
    device_class: energy
    # Set state_class in order for HA to use sensor in the Energy component
    state_class: total_increasing
    unit_of_measurement: Wh
    accuracy_decimals: 0
    filters:
    - throttle: 10s
    - multiply: 10
  
  - name: "PV3 DC current"
    device_class: energy
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
    - throttle: 10s
    - multiply: 0.1
  
  - name: "PV3 DC voltage"
    device_class: energy
    unit_of_measurement: V
    accuracy_decimals: 0
    filters:
    - throttle: 10s
  
  - name: "PV3 AC current"
    device_class: energy
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
    - throttle: 10s
    - multiply: 0.1
  
  - name: "PV3 AC voltage"
    device_class: energy
    unit_of_measurement: V
    accuracy_decimals: 0
    filters:
    - throttle: 10s
  
  - name: "PV3 Heat sink #1"
    device_class: temperature
    unit_of_measurement: °C
    filters:
    - throttle: 10s
  
  - name: "PV3 Heat sink #2"
    device_class: temperature
    unit_of_measurement: °C
    filters:
    - throttle: 10s

  - name: "PV3 ISO +"
    device_class: energy
    unit_of_measurement: kΩ
    filters:
    - throttle: 10s
  
  - name: "PV3 ISO -"
    device_class: energy
    unit_of_measurement: kΩ
    filters:
    - throttle: 10s
